-- 테이블이 존재할 경우에만 삭제 (오류 무시)
DROP TABLE vehicles;
DROP TABLE long_bus_schedule;
DROP TABLE stops CASCADE CONSTRAINTS;

-- 1. 정류장 테이블 (stops)
-- YOLO를 통해 'crowd' 값이 실시간 업데이트될 핵심 테이블
CREATE TABLE stops (
    stop_id VARCHAR2(50) PRIMARY KEY,       -- 정류장 고유 ID (예: 'baekseok', 'terminal', PK)
    stop_name VARCHAR2(100) NOT NULL,     -- 정류장 이름 (예: '백석대학교', '천안터미널')
    route_order NUMBER NOT NULL UNIQUE,     -- 정류장 순번 (겹치면 안 됨)
    crowd NUMBER(1) DEFAULT 1 NOT NULL,   -- 혼잡도 (1:낮음, 2:중간, 3:높음)

    -- crowd 컬럼은 1, 2, 3 값만 허용
    CONSTRAINT chk_stops_crowd CHECK (crowd IN (1, 2, 3))
);


-- 2. 셔틀 위치 테이블 (vehicles)
-- 실시간 버스 위치 정보 (정적 또는 실시간)
CREATE TABLE vehicles (
    vehicle_number VARCHAR2(20) PRIMARY KEY, -- 버스 차번호 (PK)
    direction VARCHAR2(10) NOT NULL,      -- 'inbound' (등교), 'outbound' (하교)
    current_stop_id VARCHAR2(50),         -- 현재/다음 정류장 ID (stops 테이블 참조)
    arrival_minutes NUMBER NOT NULL,      -- 도착 예정 (0:승하차중, -1:회송, N:N분)

    -- current_stop_id는 stops 테이블의 stop_id를 참조 (외래 키)
    -- 회송(-1)의 경우 특정 정류장이 없을 수 있으므로 NULL 허용
    FOREIGN KEY (current_stop_id) REFERENCES stops(stop_id),

    -- direction 값은 'inbound', 'outbound'만 허용
    CONSTRAINT chk_vehicles_direction CHECK (direction IN ('inbound', 'outbound'))
);


-- 3. (장거리) 통학버스 시간표 테이블 (long_bus_schedule)
-- 'long-bus'는 하이픈(-) 대신 언더바(_) 사용
-- 회의 후 세부사항이 변경될 수 있는 목업용 테이블
CREATE TABLE long_bus_schedule (
    schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 자동 증가 ID
    destination VARCHAR2(100) NOT NULL, -- 목적지 (예: '서울(잠실)', '인천')
    direction VARCHAR2(10) NOT NULL,    -- 'inbound', 'outbound'
    fare NUMBER NOT NULL,                 -- 요금
    day_type VARCHAR2(20) NOT NULL,     -- 'weekday' (평일), 'weekend' (주말), 'all'
    departure_time VARCHAR2(5) NOT NULL,  -- 출발 시간 (예: '08:30', '17:00')

    -- 제약 조건 추가
    CONSTRAINT chk_long_bus_direction CHECK (direction IN ('inbound', 'outbound')),
    CONSTRAINT chk_long_bus_day_type CHECK (day_type IN ('weekday', 'weekend', 'all'))
);

